#!/usr/bin/env python3
"""Assemble standalone serial/index.html from src/ and src/lib/."""

from pathlib import Path


ROOT = Path(__file__).resolve().parent
SRC = ROOT / "src"
LIB = SRC / "lib"
OUT = ROOT / "index.html"


def need_text(path: Path) -> str:
    if not path.is_file():
        raise FileNotFoundError(f"Missing required file: {path}")
    return path.read_text(encoding="utf-8")


def main() -> None:
    xterm_css = need_text(LIB / "xterm.min.css")
    xterm_js = need_text(LIB / "xterm.min.js")
    xterm_fit_js = need_text(LIB / "xterm-addon-fit.min.js")
    app_css = need_text(SRC / "app.css")
    body_html = need_text(SRC / "body.html")
    app_js = need_text(SRC / "app.js")

    xterm_license = """xterm.js v5.3.0 - https://github.com/xtermjs/xterm.js
Copyright (c) 2017-2022 The xterm.js authors. Licensed MIT.

xterm-addon-fit v0.8.0 - https://github.com/xtermjs/xterm.js
Copyright (c) 2019 The xterm.js authors. Licensed MIT.

Full license text: see LICENSES.md alongside this file."""

    html = f"""<!DOCTYPE html>
<!--
  Serial Monitor - standalone single-file build.
  Generated by build.py from src/. Do not edit this file directly;
  edit src/app.js, src/app.css, src/body.html, then re-run build.py.

  Bundled libraries:
  {xterm_license}
-->
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Serial Monitor</title>
<style>
/* xterm.js v5.3.0 - MIT - https://github.com/xtermjs/xterm.js */
{xterm_css}
</style>
<style>
{app_css}
</style>
</head>
<body>
{body_html}
<script>
/*! xterm.js v5.3.0 - MIT - https://github.com/xtermjs/xterm.js */
{xterm_js}
</script>
<script>
/*! xterm-addon-fit v0.8.0 - MIT - https://github.com/xtermjs/xterm.js */
{xterm_fit_js}
</script>
<script>
{app_js}
</script>
</body>
</html>
"""

    OUT.write_text(html, encoding="utf-8")
    size = OUT.stat().st_size
    print(f"Built {OUT} ({size:,} bytes / {size / 1024:.1f} KB)")


if __name__ == "__main__":
    main()
