# Assemble standalone serial/index.html from src/ + src/lib/.
# Run from this directory:   .\build.ps1
#
# Inputs:
#   src/app.css         - custom styles
#   src/body.html       - <body> contents (everything inside <body>)
#   src/app.js          - application script
#   src/lib/xterm.min.css
#   src/lib/xterm.min.js
#   src/lib/xterm-addon-fit.min.js
#   LICENSES.md         - referenced in the header comment
#
# Output:
#   index.html (standalone, ready to serve)

$ErrorActionPreference = 'Stop'

$root      = $PSScriptRoot
$src       = Join-Path $root 'src'
$lib       = Join-Path $src  'lib'
$out       = Join-Path $root 'index.html'

function Need($p) {
    if (-not (Test-Path $p)) { throw "Missing required file: $p" }
    return Get-Content -LiteralPath $p -Raw -Encoding UTF8
}

$xtermCss      = Need (Join-Path $lib 'xterm.min.css')
$xtermJs       = Need (Join-Path $lib 'xterm.min.js')
$xtermFitJs    = Need (Join-Path $lib 'xterm-addon-fit.min.js')
$appCss        = Need (Join-Path $src 'app.css')
$bodyHtml      = Need (Join-Path $src 'body.html')
$appJs         = Need (Join-Path $src 'app.js')

$xtermLicense = @'
xterm.js v5.3.0 - https://github.com/xtermjs/xterm.js
Copyright (c) 2017-2022 The xterm.js authors. Licensed MIT.

xterm-addon-fit v0.8.0 - https://github.com/xtermjs/xterm.js
Copyright (c) 2019 The xterm.js authors. Licensed MIT.

Full license text: see LICENSES.md alongside this file.
'@

$banner = @"
<!DOCTYPE html>
<!--
  Serial Monitor - standalone single-file build.
  Generated by build.ps1 from src/. Do not edit this file directly;
  edit src/app.js, src/app.css, src/body.html, then re-run build.ps1.

  Bundled libraries:
  $xtermLicense
-->
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Serial Monitor</title>
<style>
/* xterm.js v5.3.0 - MIT - https://github.com/xtermjs/xterm.js */
$xtermCss
</style>
<style>
$appCss
</style>
</head>
<body>
$bodyHtml
<script>
/*! xterm.js v5.3.0 - MIT - https://github.com/xtermjs/xterm.js */
$xtermJs
</script>
<script>
/*! xterm-addon-fit v0.8.0 - MIT - https://github.com/xtermjs/xterm.js */
$xtermFitJs
</script>
<script>
$appJs
</script>
</body>
</html>
"@

# Write as UTF-8 without BOM
$utf8NoBom = New-Object System.Text.UTF8Encoding($false)
[System.IO.File]::WriteAllText($out, $banner, $utf8NoBom)

$size = (Get-Item $out).Length
Write-Host ("Built {0} ({1:N0} bytes / {2:N1} KB)" -f $out, $size, ($size/1024)) -ForegroundColor Green
