#!/usr/bin/env python3
"""Assemble standalone ars/index.html (desktop) and ars/mobile/index.html from src/."""

from pathlib import Path


ROOT = Path(__file__).resolve().parent
SRC = ROOT / "src"
OUT = ROOT / "index.html"
MOBILE_OUT = ROOT / "mobile" / "index.html"


def need_text(path: Path) -> str:
    if not path.is_file():
        raise FileNotFoundError(f"Missing required file: {path}")
    return path.read_text(encoding="utf-8")


def build(out_path: Path, css: str, viewport_meta: str, variant: str) -> None:
    body_html = need_text(SRC / "body.html")
    app_js = need_text(SRC / "app.js")

    if variant == "desktop":
        # Phones landing on the plain URL previously got the desktop layout
        # (there was nothing to send them to mobile/) - redirect on load
        # unless the visitor has explicitly opted back into desktop via the
        # link below, remembered per-browser so it doesn't re-redirect them
        # every visit.
        extra_head = """<script>
(function () {
  if (localStorage.getItem('arsForceDesktop') === '1') return;
  if (/Mobi|iPhone|iPod/i.test(navigator.userAgent)) location.replace('mobile/');
})();
</script>"""
        site_switch = '<div class="site-switch"><a href="mobile/">Mobile site</a></div>'
    else:
        extra_head = ""
        site_switch = """<div class="site-switch"><a href="../" id="desktopSiteLink">Desktop site</a></div>
<script>
document.getElementById('desktopSiteLink').addEventListener('click', function (e) {
  e.preventDefault();
  localStorage.setItem('arsForceDesktop', '1');
  location.href = '../';
});
</script>"""

    html = f"""<!doctype html>
<!--
  ARS Console - standalone single-file build ({variant}).
  Generated by build.py from src/. Do not edit this file directly;
  edit src/app.js, src/body.html, and the relevant CSS file, then re-run build.py.
-->
<html lang="en">
<head>
<meta charset="utf-8">
{viewport_meta}
{extra_head}
<title>ARS Console</title>
<style>
{css}
</style>
</head>
<body>
{body_html}
{site_switch}
<script>
{app_js}
</script>
</body>
</html>
"""

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(html, encoding="utf-8")
    size = out_path.stat().st_size
    print(f"Built {out_path} ({size:,} bytes / {size / 1024:.1f} KB)")


def main() -> None:
    # Desktop build: no viewport meta, so it keeps rendering at its native
    # layout width in a desktop browser rather than picking up mobile-style
    # viewport scaling.
    build(OUT, need_text(SRC / "app.css"), "", "desktop")
    # Mobile build: same body.html/app.js (same element IDs drive both --
    # this is a CSS-only layout swap), plus the viewport meta tag every
    # mobile-responsive page needs to not render at desktop width and scale
    # down.
    build(
        MOBILE_OUT,
        need_text(SRC / "app-mobile.css"),
        '<meta name="viewport" content="width=device-width, initial-scale=1">',
        "mobile",
    )


if __name__ == "__main__":
    main()
