#!/usr/bin/env python3
"""Assemble standalone ars/index.html from src/."""

from pathlib import Path


ROOT = Path(__file__).resolve().parent
SRC = ROOT / "src"
OUT = ROOT / "index.html"


def need_text(path: Path) -> str:
    if not path.is_file():
        raise FileNotFoundError(f"Missing required file: {path}")
    return path.read_text(encoding="utf-8")


def main() -> None:
    app_css = need_text(SRC / "app.css")
    body_html = need_text(SRC / "body.html")
    app_js = need_text(SRC / "app.js")

    html = f"""<!doctype html>
<!--
  ARS Console - standalone single-file build.
  Generated by build.py from src/. Do not edit this file directly;
  edit src/app.js, src/app.css, src/body.html, then re-run build.py.
-->
<html lang="en">
<head>
<meta charset="utf-8">
<title>ARS Console</title>
<style>
{app_css}
</style>
</head>
<body>
{body_html}
<script>
{app_js}
</script>
</body>
</html>
"""

    OUT.write_text(html, encoding="utf-8")
    size = OUT.stat().st_size
    print(f"Built {OUT} ({size:,} bytes / {size / 1024:.1f} KB)")


if __name__ == "__main__":
    main()
