#!/usr/bin/env python3
"""Assemble standalone sillygoose/index.html from src/ and src/lib/."""

import base64
from pathlib import Path


ROOT = Path(__file__).resolve().parent
SRC = ROOT / "src"
LIB = SRC / "lib"
ASSETS = SRC / "assets"
OUT = ROOT / "index.html"


def need_text(path: Path) -> str:
    if not path.is_file():
        raise FileNotFoundError(f"Missing required file: {path}")
    return path.read_text(encoding="utf-8")


def need_bytes(path: Path) -> bytes:
    if not path.is_file():
        raise FileNotFoundError(f"Missing required file: {path}")
    return path.read_bytes()


def main() -> None:
    plotly_js = need_text(LIB / "plotly-2.27.0.min.js")
    jszip_js = need_text(LIB / "jszip-3.10.1.min.js")
    app_css = need_text(SRC / "app.css")
    body_html = need_text(SRC / "body.html")
    app_js = need_text(SRC / "app.js")

    logo_base64 = base64.b64encode(need_bytes(ASSETS / "logo.png")).decode("ascii")
    logo_data_uri = f"data:image/png;base64,{logo_base64}"
    if "{{LOGO_DATA_URI}}" not in body_html:
        raise ValueError("Missing logo placeholder in src/body.html")
    body_html = body_html.replace("{{LOGO_DATA_URI}}", logo_data_uri)

    third_party_notice = """Plotly.js v2.27.0 - https://github.com/plotly/plotly.js
Copyright (c) 2012-2023 Plotly, Inc. Licensed MIT.

JSZip v3.10.1 - https://github.com/Stuk/jszip
Copyright (c) 2009-2016 Stuart Knightley. Licensed MIT or GPLv3.

Full license notes: see LICENSES.md alongside this file."""

    html = f"""<!DOCTYPE html>
<!--
  SillyGoose Configuration Tool - standalone single-file build.
  Generated by build.py from src/. Do not edit this file directly;
  edit src/app.js, src/app.css, src/body.html, then re-run build.py.

  Bundled libraries:
  {third_party_notice}
-->
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>SillyGoose Configuration Tool</title>
<style>
{app_css}
</style>
</head>
<body>
{body_html}
<script>
/*! plotly.js v2.27.0 - MIT - https://github.com/plotly/plotly.js */
{plotly_js}
</script>
<script>
/*! JSZip v3.10.1 - MIT or GPLv3 - https://github.com/Stuk/jszip */
{jszip_js}
</script>
<script>
{app_js}
</script>
</body>
</html>
"""

    OUT.write_text(html, encoding="utf-8")
    size = OUT.stat().st_size
    print(f"Built {OUT} ({size:,} bytes / {size / 1024:.1f} KB)")


if __name__ == "__main__":
    main()
