#!/usr/bin/env python3
"""Assemble itd/index.html: one page, three tabs.

  Console    the ARS console, built from ../ars/src (the same sources as /ars, which still builds
             on its own from ars/build.py)
  Audio      the capture viewer (src/viewer.*), SD .BIN and field-tool captures
  Motor log  the UI-mode motor log viewer (src/uilog.*)

The tools were written as whole pages, so their stylesheets target html/body/header/main and
their scripts declare top-level names (both define `$`). To share one document, every
stylesheet is rewritten so each rule only applies inside its tab's panel (`:root`/`html`/`body`
become the panel itself), and every script is wrapped in its own function scope. The tools talk
to each other only through window.ITD (src/shell.js).

Edit the sources, then run:  python itd/build.py
"""

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent
SRC = ROOT / "src"
ARS = ROOT.parent / "ars" / "src"
OUT = ROOT / "index.html"


def read(path: Path) -> str:
    if not path.is_file():
        raise FileNotFoundError(f"Missing required file: {path}")
    return path.read_text(encoding="utf-8")


# ------------------------------------------------------------------------------- CSS scoping
def _scope_selector(sel: str, scope: str) -> str:
    sel = sel.strip()
    if sel in (":root", "html", "body"):
        return scope
    for root in ("html ", "body "):
        if sel.startswith(root):
            return scope + " " + sel[len(root):].strip()
    if sel == "*":
        return f"{scope}, {scope} *"
    return f"{scope} {sel}"


def _split_selectors(prelude: str):
    out, depth, cur = [], 0, ""
    for ch in prelude:
        if ch in "([":
            depth += 1
        elif ch in ")]":
            depth -= 1
        if ch == "," and depth == 0:
            out.append(cur)
            cur = ""
        else:
            cur += ch
    out.append(cur)
    return [s for s in out if s.strip()]


def _matching_brace(css: str, open_at: int) -> int:
    depth = 0
    for i in range(open_at, len(css)):
        if css[i] == "{":
            depth += 1
        elif css[i] == "}":
            depth -= 1
            if depth == 0:
                return i
    raise ValueError("unbalanced braces in CSS")


def scope_css(css: str, scope: str) -> str:
    css = re.sub(r"/\*.*?\*/", "", css, flags=re.S)
    out, i = [], 0
    while True:
        brace = css.find("{", i)
        if brace < 0:
            break
        prelude = css[i:brace].strip()
        end = _matching_brace(css, brace)
        inner = css[brace + 1:end]
        if prelude.startswith(("@media", "@supports")):
            out.append(f"{prelude} {{\n{scope_css(inner, scope)}}}\n")
        elif prelude.startswith("@"):
            out.append(f"{prelude} {{{inner}}}\n")   # @keyframes, @font-face: untouched
        else:
            sels = ", ".join(_scope_selector(s, scope) for s in _split_selectors(prelude))
            out.append(f"{sels} {{{inner}}}\n")
        i = end + 1
    return "".join(out)


def wrap_js(js: str, name: str) -> str:
    return f"/* ---- {name} ---- */\n(function () {{\n{js}\n}})();\n"


# ------------------------------------------------------------------------------- page
def main() -> None:
    styles = "\n".join([
        read(SRC / "shell.css"),
        scope_css(read(ARS / "app.css"), "#tab-console"),
        # the console's phone layout, applied by width instead of a separate page
        "@media (max-width: 760px) {\n" + scope_css(read(ARS / "app-mobile.css"), "#tab-console") + "}\n",
        scope_css(read(SRC / "viewer.css"), "#tab-audio"),
        scope_css(read(SRC / "uilog.css"), "#tab-motorlog"),
    ])
    scripts = "\n".join([
        read(SRC / "shell.js"),
        wrap_js(read(ARS / "app.js"), "console (ars/src/app.js)"),
        wrap_js(read(SRC / "viewer.js"), "audio viewer"),
        wrap_js(read(SRC / "uilog.js"), "motor log"),
        read(SRC / "tabs.js"),
    ])
    html = f"""<!doctype html>
<!--
  ITD tools - standalone single-file build. Generated by itd/build.py from itd/src and ars/src.
  Do not edit this file directly; edit the sources and re-run build.py.
-->
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">
<title>ITD Tools</title>
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=IBM+Plex+Sans:wght@400;500;600&family=IBM+Plex+Mono:wght@400;500&display=swap">
<style>
{styles}
</style>
</head>
<body class="itd">
<nav class="itd-tabs" role="tablist" aria-label="Tools">
  <span class="itd-brand">ITD</span>
  <button class="itd-tab" role="tab" data-tab="console" aria-controls="tab-console">Console</button>
  <button class="itd-tab" role="tab" data-tab="audio" aria-controls="tab-audio">Audio viewer</button>
  <button class="itd-tab" role="tab" data-tab="motorlog" aria-controls="tab-motorlog">Motor log</button>
  <span class="itd-conn" id="itdConn"><i></i> disconnected</span>
</nav>
<section class="itd-panel" id="tab-console" role="tabpanel" aria-label="Console">
{read(ARS / "body.html")}
</section>
<section class="itd-panel" id="tab-audio" role="tabpanel" aria-label="Audio viewer" hidden>
{read(SRC / "viewer.html")}
</section>
<section class="itd-panel" id="tab-motorlog" role="tabpanel" aria-label="Motor log" hidden>
{read(SRC / "uilog.html")}
</section>
<script>
{scripts}
</script>
</body>
</html>
"""
    OUT.write_text(html, encoding="utf-8")
    size = OUT.stat().st_size
    print(f"Built {OUT} ({size:,} bytes / {size / 1024:.1f} KB)")


if __name__ == "__main__":
    main()
