#!/usr/bin/env python3
"""Assemble standalone map/index.html from src/."""

from pathlib import Path


ROOT = Path(__file__).resolve().parent
SRC = ROOT / "src"
LIB = SRC / "lib"
OUT = ROOT / "index.html"


def need_text(path: Path) -> str:
    if not path.is_file():
        raise FileNotFoundError(f"Missing required file: {path}")
    return path.read_text(encoding="utf-8")


def main() -> None:
    leaflet_css = need_text(LIB / "leaflet.css")
    leaflet_js = need_text(LIB / "leaflet.js")
    app_css = need_text(SRC / "app.css")
    body_html = need_text(SRC / "body.html")
    app_js = need_text(SRC / "app.js")

    leaflet_license = """Leaflet v1.9.4 - https://leafletjs.com
Copyright (c) 2010-2023, Vladimir Agafonkin
Copyright (c) 2010-2011, CloudMade
Licensed BSD-2-Clause. Full license text: see LICENSES.md."""

    html = f"""<!doctype html>
<!--
  Map Plotter - standalone single-file build.
  Generated by build.py from src/. Do not edit this file directly;
  edit src/app.js, src/app.css, src/body.html, then re-run build.py.

  Bundled libraries:
  {leaflet_license}
-->
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Map Plotter</title>
<style>
/* Leaflet v1.9.4 - BSD-2-Clause - https://leafletjs.com */
{leaflet_css}
</style>
<style>
{app_css}
</style>
</head>
<body>
{body_html}
<script>
/*! Leaflet v1.9.4 - BSD-2-Clause - https://leafletjs.com */
{leaflet_js}
</script>
<script>
{app_js}
</script>
</body>
</html>
"""

    OUT.write_text(html, encoding="utf-8")
    size = OUT.stat().st_size
    print(f"Built {OUT} ({size:,} bytes / {size / 1024:.1f} KB)")


if __name__ == "__main__":
    main()
